name: example
description: An exmple of entity_serializer
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  copy_with_extension: ^5.0.0

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  entity_serializer:
    path: ../
