name: entity_serializer
description: CLI and Builder tool for creating entities classes and serializers from xml description.
version: 0.0.3
homepage: https://github.com/TheTosters/entity_serializer
repository: https://github.com/TheTosters/entity_serializer

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  xml: ^6.2.2
  args: ^2.3.1
  path: ^1.8.0
  recase: ^4.1.0
  collection: ^1.17.0
  build: ^2.3.1
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  build_config: ^1.1.1
  copy_with_extension_gen: ^5.0.0